import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowUpRight, BellRing, CalendarDays, ChevronDown, Clock3, CreditCard, IndianRupee, LayoutDashboard, PackageCheck, Plus, ShoppingBag, Users, UtensilsCrossed } from "lucide-react";
import { getDashboardStats } from "../api";

const statusStyles = { Delivered: "bg-emerald-50 text-emerald-700", Preparing: "bg-amber-50 text-amber-700", "On the way": "bg-sky-50 text-sky-700", Cancelled: "bg-red-50 text-red-600" };
const labels = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

function SalesChart({ values }) {
  const max = Math.max(...values, 1);
  const points = values.map((value, index) => `${18 + index * 52},${138 - (value / max) * 94}`).join(" ");
  const area = `18,142 ${points} 330,142`;
  return <div className="relative mt-5 h-56 min-w-[510px]">
    <svg viewBox="0 0 348 172" className="h-full w-full overflow-visible" role="img" aria-label="Weekly revenue graph">
      <defs><linearGradient id="salesFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ff6e4a" stopOpacity=".28" /><stop offset="100%" stopColor="#ff6e4a" stopOpacity="0" /></linearGradient><filter id="salesGlow"><feGaussianBlur stdDeviation="2" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>
      {[30, 70, 110, 150].map((line) => <line key={line} x1="12" x2="336" y1={line} y2={line} stroke="#eee9e6" strokeDasharray="3 5" />)}
      <polygon points={area} fill="url(#salesFill)" />
      <polyline points={points} fill="none" stroke="#ff6e4a" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" filter="url(#salesGlow)" />
      {values.map((value, index) => { const [x, y] = points.split(" ")[index].split(","); return <g key={labels[index]} className="chart-dot"><circle cx={x} cy={y} r="6" fill="#fff" stroke="#ff6e4a" strokeWidth="3" /><title>{`${labels[index]}: Rs. ${value}k`}</title></g>; })}
    </svg>
    <div className="absolute inset-x-0 bottom-0 flex justify-between px-3 text-[11px] font-medium text-ink-500">{labels.map((label) => <span key={label}>{label}</span>)}</div>
  </div>;
}

export default function Dashboard() {
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState("This week");
  useEffect(() => { getDashboardStats().then((data) => { setStats(data); setLoading(false); }); }, []);

  const orderSplit = useMemo(() => {
    const orders = stats?.recentOrders || [];
    return { delivered: orders.filter((order) => order.status === "Delivered").length, active: orders.filter((order) => ["Preparing", "On the way"].includes(order.status)).length, cancelled: orders.filter((order) => order.status === "Cancelled").length };
  }, [stats]);
  const cards = stats ? [
    { label: "Gross revenue", value: `Rs. ${stats.totalRevenue.toLocaleString()}`, trend: "+8.1%", icon: IndianRupee, iconClass: "bg-primary/10 text-primary" },
    { label: "Total orders", value: stats.totalOrders.toLocaleString(), trend: "+12.4%", icon: ShoppingBag, iconClass: "bg-violet-50 text-violet-600" },
    { label: "New customers", value: stats.totalCustomers.toLocaleString(), trend: "+4.6%", icon: Users, iconClass: "bg-sky-50 text-sky-600" },
    { label: "Menu availability", value: `${stats.totalFoods} items`, trend: "All synced", icon: UtensilsCrossed, iconClass: "bg-emerald-50 text-emerald-600" },
  ] : [];

  return <div className="dashboard-shell animate-fadeIn space-y-5">
    <section className="dashboard-hero overflow-hidden rounded-3xl p-5 text-white sm:p-7"><div className="dashboard-hero-orb" /><div className="relative z-10 flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1 text-xs font-semibold text-white/90"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-300" /> Live restaurant operations</div><h1 className="font-display text-3xl font-extrabold tracking-tight sm:text-4xl text-white">Control centre</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/80">Monitor sales, orders, kitchen activity and customer growth from one polished admin workspace.</p></div><div className="grid grid-cols-2 gap-3 sm:flex"><Link to="/add-food" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-ink-900 transition hover:-translate-y-0.5 hover:shadow-lg"><Plus size={17} /> Add food</Link><Link to="/orders" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-sm font-bold text-white transition hover:bg-white/20"><PackageCheck size={17} /> Manage orders</Link></div></div></section>

    <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 2xl:grid-cols-4">{loading ? Array.from({ length: 4 }).map((_, index) => <div key={index} className="card h-36 animate-pulse bg-ink-100/60 dark:bg-slate-800" />) : cards.map(({ label, value, trend, icon: Icon, iconClass }, index) => <article key={label} className={`metric-card card group animate-rise-in animate-delay-${index > 2 ? 2 : index}`}><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-ink-500 dark:text-slate-400">{label}</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight text-ink-900 dark:text-slate-100">{value}</h2></div><span className={`grid h-11 w-11 place-items-center rounded-2xl ${iconClass} transition-transform duration-200 group-hover:scale-110`}><Icon size={20} /></span></div><p className="mt-4 flex items-center gap-1 text-xs font-semibold text-emerald-600"><ArrowUpRight size={14} /> {trend}<span className="ml-1 font-medium text-ink-500 dark:text-slate-400">vs last week</span></p></article>)}</section>

    <section className="grid grid-cols-1 gap-5 2xl:grid-cols-12"><article className="card overflow-hidden 2xl:col-span-8"><div className="flex flex-col gap-3 border-b border-ink-100 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Analytics</p><h2 className="mt-1 text-lg font-bold text-ink-900 dark:text-slate-100">Revenue performance</h2><p className="text-xs text-ink-500 dark:text-slate-400">Sales trend from the last seven days.</p></div><label className="relative inline-flex items-center self-start"><CalendarDays size={15} className="pointer-events-none absolute left-3 text-ink-500 dark:text-slate-400" /><select value={period} onChange={(event) => setPeriod(event.target.value)} className="appearance-none rounded-xl border border-ink-100 bg-ink-50 py-2 pl-9 pr-8 text-xs font-semibold text-ink-700 outline-none focus:border-primary dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"><option>This week</option><option>This month</option><option>This quarter</option></select><ChevronDown size={14} className="pointer-events-none absolute right-2.5 text-ink-500 dark:text-slate-400" /></label></div><div className="mt-4 flex items-end justify-between"><div><p className="text-3xl font-extrabold tracking-tight text-ink-900 dark:text-slate-100">Rs. {(stats?.revenueTrend.reduce((total, value) => total + value, 0) || 0)}k</p><p className="mt-1 text-xs font-semibold text-emerald-600">+18.2% <span className="ml-1 font-medium text-ink-500 dark:text-slate-400">compared with prior period</span></p></div><div className="hidden rounded-xl bg-emerald-50 px-3 py-2 text-right sm:block dark:bg-emerald-500/10"><p className="text-[11px] font-semibold text-emerald-700 dark:text-emerald-300">Best day</p><p className="text-sm font-bold text-emerald-800 dark:text-emerald-200">Sunday · Rs. 32k</p></div></div><div className="overflow-x-auto"><SalesChart values={stats?.revenueTrend || [12, 19, 14, 22, 28, 24, 32]} /></div></article>
      <article className="card 2xl:col-span-4"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Order health</p><h2 className="mt-1 text-lg font-bold text-ink-900 dark:text-slate-100">Fulfilment status</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary-50 text-primary"><LayoutDashboard size={18} /></span></div><div className="my-5 flex items-center gap-5"><div className="relative grid h-28 w-28 shrink-0 place-items-center rounded-full" style={{ background: `conic-gradient(#10b981 0 ${(orderSplit.delivered / 5) * 360}deg, #ff6e4a ${(orderSplit.delivered / 5) * 360}deg ${((orderSplit.delivered + orderSplit.active) / 5) * 360}deg, #f3f0ee ${((orderSplit.delivered + orderSplit.active) / 5) * 360}deg 360deg)` }}><div className="grid h-[86px] w-[86px] place-items-center rounded-full bg-white text-center dark:bg-slate-900"><span><strong className="block text-xl text-ink-900 dark:text-slate-100">{stats?.recentOrders.length || 0}</strong><small className="text-[10px] font-semibold uppercase text-ink-500 dark:text-slate-400">Orders</small></span></div></div><div className="space-y-3 text-sm"><p className="flex items-center justify-between gap-5"><span className="flex items-center gap-2 text-ink-600 dark:text-slate-300"><i className="h-2 w-2 rounded-full bg-emerald-500" /> Delivered</span><b>{orderSplit.delivered}</b></p><p className="flex items-center justify-between gap-5"><span className="flex items-center gap-2 text-ink-600 dark:text-slate-300"><i className="h-2 w-2 rounded-full bg-primary" /> In progress</span><b>{orderSplit.active}</b></p><p className="flex items-center justify-between gap-5"><span className="flex items-center gap-2 text-ink-600 dark:text-slate-300"><i className="h-2 w-2 rounded-full bg-ink-300" /> Cancelled</span><b>{orderSplit.cancelled}</b></p></div></div><Link to="/orders" className="flex items-center justify-between rounded-xl bg-ink-50 px-4 py-3 text-sm font-bold text-ink-700 transition hover:bg-primary-50 hover:text-primary dark:bg-slate-800 dark:text-slate-200"><span>Open order board</span><ArrowUpRight size={16} /></Link></article></section>

    <section className="grid grid-cols-1 gap-5 2xl:grid-cols-12"><article className="card overflow-x-auto 2xl:col-span-8"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold dark:text-slate-100">Order activity</h2><p className="text-xs text-ink-500 dark:text-slate-400">Latest orders from your restaurant.</p></div><Link to="/orders" className="text-sm font-bold text-primary hover:underline">See all orders</Link></div><table className="w-full min-w-[600px] text-sm"><thead><tr className="border-b border-ink-100 text-left text-xs font-semibold uppercase tracking-wide text-ink-500 dark:border-slate-800 dark:text-slate-400"><th className="pb-3">Order</th><th className="pb-3">Customer</th><th className="pb-3">Amount</th><th className="pb-3">Payment</th><th className="pb-3 text-right">Status</th></tr></thead><tbody>{stats?.recentOrders.map((order) => <tr key={order.id} className="table-row-hover border-b border-ink-100/70 last:border-0 dark:border-slate-800"><td className="py-3.5 font-bold text-ink-800 dark:text-slate-100">{order.id}</td><td className="py-3.5 text-ink-600 dark:text-slate-300">{order.customer}</td><td className="py-3.5 font-semibold text-ink-800 dark:text-slate-100">Rs. {order.amount}</td><td className="py-3.5 text-ink-500 dark:text-slate-400">{order.payment || "UPI"}</td><td className="py-3.5 text-right"><span className={`badge ${statusStyles[order.status]}`}>{order.status}</span></td></tr>)}</tbody></table></article>
      <aside className="card 2xl:col-span-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Today</p><h2 className="mt-1 text-lg font-bold text-ink-900 dark:text-slate-100">Operations feed</h2></div><BellRing size={19} className="text-primary" /></div><div className="mt-5 space-y-4"><div className="feed-item"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><CreditCard size={16} /></span><p><b>Payment settled</b><small>Rs. 18,420 received via online payments</small></p></div><div className="feed-item"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-600"><Clock3 size={16} /></span><p><b>{stats?.activeOrders || 0} orders in progress</b><small>Kitchen queue needs an update</small></p></div><div className="feed-item"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sky-50 text-sky-600"><Users size={16} /></span><p><b>Customer growth is healthy</b><small>4.6% more returning customers this week</small></p></div></div><Link to="/customers" className="mt-5 inline-flex text-sm font-bold text-primary hover:underline">View customers <ArrowUpRight size={15} className="ml-1" /></Link></aside></section>
  </div>;
}
